import { pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// MODULE 5 — DEVICES (optional push + anonymous personalisation)
//
// NOTE: Premium is entirely app-side (RevenueCat SDK).
// This table is ONLY for optional push notifications + anonymous
// personalisation. No entitlement or RevenueCat data stored here.
// ---------------------------------------------------------------------------

export const devices = pgTable('devices', {
  id: uuid('id').primaryKey().defaultRandom(),
  // Opaque anonymous ID generated by the client — never a real user ID.
  deviceId: text('device_id').unique().notNull(),
  platform: text('platform'), // ios | android
  country: text('country'),
  locale: text('locale'),
  timezone: text('timezone'),
  // Expo push token — optional; null means no push for this device.
  pushToken: text('push_token'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  lastSeen: timestamp('last_seen', { withTimezone: true }),
});
